"""
pulse_story.py, the deterministic insight engine for the Dana Point PULSE board view.

Every section and every visual on the page carries a key question and a
written answer. The answers are computed here, from the same window-aware
figures the charts draw (see pulse_data.py), so they change with the data
window and never disagree with the tiles or charts beside them. Nothing is
generated by a language model on this path; the optional "Ask about this
section" buttons on the page are the only AI calls, and they are handed this
module's text as context so their answers stay consistent with the page.

Writing rules, from the Visit Dana Point voice and the project CLAUDE.md:
plain executive English, specific numbers with their comparison and period,
no em dashes, no exclamation marks, calibrated language for relationships
("moves with", never "drives"), and a named source on every claim.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd

import pulse_data as pdx


# ---------------------------------------------------------------------------
# Number formatting
# ---------------------------------------------------------------------------

def pct(v, d: int = 1) -> str:
    return "n/a" if v is None or pd.isna(v) else f"{v:.{d}f}%"


def spct(v, d: int = 1) -> str:
    """Signed percent change, e.g. +8.8%."""
    return "n/a" if v is None or pd.isna(v) else f"{v:+.{d}f}%"


def pts(v, d: int = 1) -> str:
    return "n/a" if v is None or pd.isna(v) else f"{v:+.{d}f} pts"


def usd(v, d: int = 0) -> str:
    return "n/a" if v is None or pd.isna(v) else f"${v:,.{d}f}"


def usd_big(v) -> str:
    if v is None or pd.isna(v):
        return "n/a"
    v = float(v)
    if abs(v) >= 1e9:
        return f"${v / 1e9:.2f}B"
    if abs(v) >= 1e6:
        return f"${v / 1e6:.1f}M"
    if abs(v) >= 1e3:
        return f"${v / 1e3:.0f}K"
    return f"${v:,.0f}"


def num_big(v) -> str:
    if v is None or pd.isna(v):
        return "n/a"
    v = float(v)
    if abs(v) >= 1e6:
        return f"{v / 1e6:.2f}M"
    if abs(v) >= 1e3:
        return f"{v / 1e3:.0f}K"
    return f"{v:,.0f}"


def direction(v, up="up", down="down", flat="flat", tol: float = 0.05) -> str:
    if v is None or pd.isna(v):
        return flat
    return up if v > tol else down if v < -tol else flat


def mag(v, d: int = 1) -> str:
    """Unsigned percent for use after a direction word ("up 12.9%")."""
    return "n/a" if v is None or pd.isna(v) else f"{abs(v):.{d}f}%"


def updown(v, tol: float = 0.05) -> str:
    return direction(v, "up", "down", "flat", tol)


DAY_NAMES = {"Mon": "Monday", "Tue": "Tuesday", "Wed": "Wednesday", "Thu": "Thursday",
             "Fri": "Friday", "Sat": "Saturday", "Sun": "Sunday"}


def plural(n: int, word: str, many: str | None = None) -> str:
    return f"{n} {word if n == 1 else (many or word + 's')}"


def days_phrase(n: int) -> str:
    if n <= 0:
        return "today"
    if n == 1:
        return "tomorrow"
    return f"in {n} days"


def _clean_market(name: str) -> str:
    fixes = {"Phoenix -Prescott": "Phoenix", "San Francisco-Oak-San Jose": "San Francisco Bay Area",
             "Dallas-Ft. Worth": "Dallas-Fort Worth", "Portland- OR": "Portland, Ore.",
             "Sacramnto-Stkton-Modesto": "Sacramento", "Washington-DC -Hagrstwn": "Washington, D.C.",
             "Boston -Manchester": "Boston", "Seattle-Tacoma": "Seattle"}
    return fixes.get(name, name)


clean_market = _clean_market


# ---------------------------------------------------------------------------
# The page model: every figure the page shows, computed once per run
# ---------------------------------------------------------------------------

@dataclass
class Model:
    window: pdx.Window
    daily: pd.DataFrame
    monthly: pd.DataFrame
    hotel: dict | None
    trend: pd.DataFrame
    dow: pd.DataFrame
    wk: dict | None
    compression: pd.DataFrame
    momentum: dict | None
    peers: dict | None
    bench: dict | None
    multiyear: pd.DataFrame
    segments: dict | None
    dfy_monthly: pd.DataFrame
    dfy: dict | None
    dfy_trend: pd.DataFrame
    link: dict | None
    markets: pd.DataFrame
    categories: pd.DataFrame
    profile: dict
    ads: dict | None
    ad_mix: pd.DataFrame
    events: pd.DataFrame
    group: dict | None
    insight: dict | None
    fresh: dict
    miles: dict = field(default_factory=dict)
    text: dict = field(default_factory=dict)


def _miles_from_dana_point(coords: dict | None) -> dict:
    import math
    if not coords:
        return {}
    lat0, lon0 = math.radians(33.467), math.radians(-117.698)
    out = {}
    for k, (lat, lon) in coords.items():
        la, lo = math.radians(lat), math.radians(lon)
        a = math.sin((la - lat0) / 2) ** 2 + math.cos(lat0) * math.cos(la) * math.sin((lo - lon0) / 2) ** 2
        out[k] = 3958.8 * 2 * math.asin(math.sqrt(a))
    return out


def build_model(conn, months: float, start_iso: str | None, end_iso: str | None, label: str,
                dma_coords: dict | None = None) -> Model | None:
    daily = pdx.hotel_daily(conn)
    if daily is None or daily.empty:
        return None
    monthly = pdx.hotel_monthly(conn)
    w = pdx.resolve_window(daily["date"].max(), months, start_iso, end_iso, label)
    dow = pdx.day_of_week(daily, w)
    dm = pdx.datafy_monthly(conn)
    markets = pdx.datafy_markets(conn)
    ads = pdx.advertising(conn)
    m = Model(
        window=w, daily=daily, monthly=monthly,
        hotel=pdx.hotel_window(daily, monthly, w),
        trend=pdx.hotel_trend(daily, monthly, w),
        dow=dow, wk=pdx.weekend_gap(dow),
        compression=pdx.compression_by_quarter(daily, 8),
        momentum=pdx.momentum(daily),
        peers=pdx.peer_window(pdx.peer_weekly(conn), w),
        bench=pdx.benchmark_ytd(conn, daily),
        multiyear=pdx.costar_multiyear(conn),
        segments=pdx.costar_segments(conn, w),
        dfy_monthly=dm, dfy=pdx.datafy_window(dm, w), dfy_trend=pdx.datafy_trend(dm, w),
        link=pdx.hotel_vs_visitor_spend(monthly, dm),
        markets=markets, categories=pdx.datafy_categories(conn), profile=pdx.datafy_profile(conn),
        ads=ads, ad_mix=pdx.ad_vs_spend_markets(ads, markets),
        events=pdx.event_last_year(daily, pdx.upcoming_events(conn)),
        group=pdx.group_mix_latest(conn), insight=pdx.forward_insight(conn),
        fresh=pdx.freshness(conn),
        miles=_miles_from_dana_point(dma_coords),
    )
    m.text = write_all(m)
    return m


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------

def _window_phrase(m: Model) -> str:
    h = m.hotel
    if h and h.get("start") is not None:
        return f"{pdx.fmt_date(h['start'])} to {pdx.fmt_date(h['end'])}"
    return m.window.span_text()


def write_snapshot(m: Model) -> dict:
    h, wk = m.hotel, m.wk
    out = {
        "question": "Are Dana Point hotels filling more rooms, at better rates, than a year ago?",
        "answer": "Hotel performance data is not available for this window yet.",
        "occ_q": "How did occupancy track against the same months last year?",
        "occ_a": "",
        "adr_q": "Is rate carrying the gain, or occupancy?",
        "adr_a": "",
        "dow_q": "Which nights sell best, and where is the opening?",
        "dow_a": "",
    }
    if not h:
        return out
    span = _window_phrase(m)
    lead = (f"For {span}, the VDP Select hotels ran {pct(h['occ'])} occupancy at a {usd(h['adr'])} "
            f"average daily rate, for {usd(h['revpar'])} in revenue per available room (RevPAR).")
    if h.get("prior"):
        occ_word = ("sold more rooms" if h["occ_pts"] > 0.05 else "sold fewer rooms" if h["occ_pts"] < -0.05
                    else "sold about the same share of rooms")
        adr_word = ("raised rate" if h["adr_pct"] > 0.05 else "gave back rate" if h["adr_pct"] < -0.05 else "held rate")
        rv = h["revpar_pct"]
        rv_word = f"lifting RevPAR {mag(rv)}" if rv > 0.05 else f"leaving RevPAR down {mag(rv)}" if rv < -0.05 else "leaving RevPAR flat"
        body = (f" Against the same period last year, hotels {occ_word} ({pts(h['occ_pts'])}) and {adr_word} "
                f"({spct(h['adr_pct'])}), {rv_word}.")
        if h.get("rev_from_adr_pts") is not None and h.get("rev_from_occ_pts") is not None:
            ra, ro = h["rev_from_adr_pts"], h["rev_from_occ_pts"]
            if rv > 0.5 and ra > 0 and ro >= 0:
                if ra >= ro:
                    body += (f" Rate did most of the work: about {ra:.1f} of the {abs(rv):.1f} percentage points came "
                             f"from ADR and {ro:.1f} from rooms sold.")
                else:
                    body += (f" Occupancy did most of the work: about {ro:.1f} of the {abs(rv):.1f} percentage points "
                             f"came from rooms sold and {ra:.1f} from ADR.")
            else:
                body += f" The change splits into about {ra:+.1f} points from rate and {ro:+.1f} from rooms sold."
    else:
        body = " A like-for-like prior-year comparison is not available for this window."
    comp = ""
    if h.get("d80") is not None:
        inc = f", including {plural(h['d90'], 'night')} at 90% or higher" if h.get("d90") else ""
        vs = ""
        if h.get("prior") and h["prior"].get("d80") is not None and h.get("method") == "daily":
            dn = h["d80"] - h["prior"]["d80"]
            vs = (f" ({dn:+d} {'night' if abs(dn) == 1 else 'nights'} versus last year)" if dn else " (level with last year)")
        comp = f" {plural(h['d80'], 'night')} reached 80% occupancy or higher{inc}{vs}."
    bench = ""
    b = m.bench
    if b and b.get("rgi_sub"):
        gap = b["rgi_sub"] - 100
        bench = (f" Year to date, Dana Point hotels earn {abs(gap):.0f}% {'more' if gap >= 0 else 'less'} RevPAR than the "
                 f"Newport Beach/Dana Point submarket as a whole (CoStar).")
    out["answer"] = lead + body + comp + bench

    # Occupancy trend
    t = m.trend
    if t is not None and not t.empty and "occ_ly" in t:
        tt = t.dropna(subset=["occ_ly"])
        if not tt.empty:
            gap = tt["occ"] - tt["occ_ly"]
            ahead = int((gap > 0.5).sum())
            best = tt.loc[gap.idxmax()]
            worst = tt.loc[gap.idxmin()]
            is_month = t["grain"].iloc[0] == "month"
            unit, prep = ("months", "in") if is_month else ("days", "on")
            out["occ_a"] = (f"Occupancy beat last year in {ahead} of {len(tt)} {unit}. The strongest gain came {prep} "
                            f"{best['label']} ({pts(best['occ'] - best['occ_ly'])}); the softest stretch was "
                            f"{worst['label']} ({pts(worst['occ'] - worst['occ_ly'])}).")
            if m.momentum and m.momentum.get("occ_pts") is not None:
                mo = m.momentum
                out["occ_a"] += (f" The most recent four weeks, through {pdx.fmt_date(mo['end'])}, ran "
                                 f"{pct(mo['occ'])} occupancy, {pts(mo['occ_pts'])} year over year.")
    # Rate
    if h.get("prior"):
        tt = t.dropna(subset=["adr_ly"]) if t is not None and not t.empty else pd.DataFrame()
        up = int((tt["adr"] > tt["adr_ly"]).sum()) if not tt.empty else 0
        unit = "months" if (t is not None and not t.empty and t["grain"].iloc[0] == "month") else "days"
        out["adr_a"] = (f"ADR averaged {usd(h['adr'])}, {spct(h['adr_pct'])} on last year"
                        + (f", and rate was higher than last year in {up} of {len(tt)} {unit}" if len(tt) and up
                           else f", and rate trailed last year in all {len(tt)} {unit}" if len(tt) else "")
                        + ". "
                        f"Room revenue for the comp set totaled {usd_big(h['revenue'])}"
                        + (f" ({spct(h.get('revenue_pct'))})." if h.get("totals_comparable") else
                           ". The comp set's room count changed between the two periods, so revenue totals are not "
                           "compared; the per-room figures above are."))
        if h.get("rev_from_adr_pts") is not None:
            share = h["rev_from_adr_pts"] / h["revpar_pct"] * 100 if h.get("revpar_pct") else None
            if share is not None and h["revpar_pct"] > 0.5 and 0 <= share <= 100:
                out["adr_a"] += f" Roughly {share:.0f}% of the RevPAR gain is price and the rest is volume."
    # Day of week
    if wk:
        out["dow_a"] = (f"Friday and Saturday nights ran {pct(wk['weekend_occ'])} occupancy at {usd(wk['weekend_adr'])}, "
                        f"against {pct(wk['midweek_occ'])} at {usd(wk['midweek_adr'])} Sunday through Thursday: a "
                        f"{wk['occ_gap']:.1f}-point occupancy gap, with weekend rates {mag(wk['adr_premium_pct'])} higher. "
                        f"{DAY_NAMES.get(wk['best'], wk['best'])} sells best ({pct(wk['best_occ'])}); "
                        f"{DAY_NAMES.get(wk['worst'], wk['worst'])} is the softest night "
                        f"({pct(wk['worst_occ'])}), which is where midweek and length-of-stay offers have the most room to add revenue.")
    return out


def write_visitors(m: Model) -> dict:
    d, prof = m.dfy, m.profile or {}
    out = {
        "question": "Who is visiting, where are they coming from, and what are they spending?",
        "answer": "Datafy visitor data is not available yet.",
        "spend_q": "Is visitor spending growing?",
        "spend_a": "",
        "mkt_q": "Which markets send the most visitor spending?",
        "mkt_a": "",
        "cat_q": "Where does each visitor dollar go?",
        "cat_a": "",
        "ads_q": "Is paid media reaching the markets that spend the most?",
        "ads_a": "",
    }
    if d and d.get("spend") is not None:
        span = (f"{pdx.fmt_month(d['first'])} to {pdx.fmt_month(d['last'])}" if d["n_months"] > 1
                else pdx.fmt_month(d["first"]))
        span = (f"from {pdx.fmt_month(d['first'])} through {pdx.fmt_month(d['last'])}" if d["n_months"] > 1
                else f"in {pdx.fmt_month(d['first'])}")
        a = f"Visitors spent {usd_big(d['spend'])} in Dana Point {span}"
        if d.get("spend_pct") is not None:
            a += f", {spct(d['spend_pct'])} on the same {'month' if d['n_months'] == 1 else 'months'} last year"
        a += "."
        if d.get("visitor_days") and d.get("vd_pct") is not None:
            # Datafy's monthly spend is card-observed spending and its visitor days
            # are modeled from location data, so only the two growth rates are
            # compared; their ratio is not presented as a dollars-per-day figure.
            if (d.get("spvd_pct") or 0) > 1 and d["vd_pct"] > -0.5:
                a += (f" Visitor days {updown(d['vd_pct'])} {mag(d['vd_pct'])} to {num_big(d['visitor_days'])}, so spending "
                      f"grew faster than visits: each visitor day carried more spending than a year earlier.")
            elif (d.get("spvd_pct") or 0) < -1:
                a += (f" Visitor days {updown(d['vd_pct'])} {mag(d['vd_pct'])} to {num_big(d['visitor_days'])}, faster than "
                      f"spending, so each visitor day carried less spending than a year earlier.")
            else:
                a += (f" Visitor days {updown(d['vd_pct'])} {mag(d['vd_pct'])} to {num_big(d['visitor_days'])}, in step "
                      f"with spending.")
        if d.get("fallback"):
            a = (f"Datafy reports monthly and has not published a month inside this window yet. The latest month on file, "
                 f"{pdx.fmt_month(d['last'])}, recorded {usd_big(d['spend'])} in visitor spend.")
        out["spend_a"] = a
        hotel = m.hotel
        link = m.link
        tie = ""
        if (hotel and hotel.get("revenue_pct") is not None and hotel.get("totals_comparable")
                and d.get("spend_pct") is not None and not d.get("fallback")):
            tie = (f" Hotel room revenue for the comp set moved {spct(hotel['revenue_pct'])} over the hotel window, "
                   f"so the destination-wide spending gain is running ahead of the hotel gain.") if d["spend_pct"] > hotel["revenue_pct"] + 2 else (
                   f" Hotel room revenue for the comp set moved {spct(hotel['revenue_pct'])}, in step with visitor spending.")
        if link:
            tie += (f" Across {link['n']} months of shared history, monthly hotel room revenue and visitor spending move "
                    f"together (correlation {link['r']:.2f}); related, but not proof that one causes the other.")
        out["spend_a"] += tie

    # Profile + headline
    mk = m.markets
    parts = []
    if d and d.get("spend") is not None:
        parts.append(out["spend_a"].split(". ")[0] + ".")
    if mk is not None and not mk.empty:
        top = mk.iloc[0]
        top3 = mk.head(3)
        parts.append(f"{clean_market(top['dma'])} is the largest source of visitor spending at {pct(top['share_pct'])}, "
                     f"and the top three markets together deliver {pct(top3['share_pct'].sum())}.")
    if prof.get("out_of_state_pct") is not None:
        los = f", and the average trip lasts {prof['avg_los']:.1f} days" if prof.get("avg_los") else ""
        parts.append(f"About {prof['out_of_state_pct']:.0f}% of visitor spending comes from outside California{los}.")
    if parts:
        out["answer"] = " ".join(parts)

    if mk is not None and len(mk) > 1:
        top, nxt = mk.iloc[0], mk.iloc[1]
        ratio = top["share_pct"] / nxt["share_pct"] if nxt["share_pct"] else None
        lead = (f"roughly twice the next market, {clean_market(nxt['dma'])} ({pct(nxt['share_pct'])})"
                if ratio and 1.7 <= ratio <= 2.4 else f"ahead of {clean_market(nxt['dma'])} ({pct(nxt['share_pct'])})")
        a = f"{clean_market(top['dma'])} leads at {pct(top['share_pct'])} of visitor spending, {lead}."
        fly = mk[mk["dma"].map(lambda x: (m.miles or {}).get(x, 0) > 500)]
        if not fly.empty:
            a += (f" Markets more than 500 miles away, led by {clean_market(fly.iloc[0]['dma'])}, supply "
                  f"{pct(fly['share_pct'].sum())} of spending among the top {len(mk)}, so Dana Point draws a meaningful "
                  f"fly-in audience beyond the Southern California drive market.")
        a += f" Datafy, {pdx.fmt_month(top['report_period_start'])} to {pdx.fmt_month(top['report_period_end'])}."
        out["mkt_a"] = a
    cats = m.categories
    if cats is not None and not cats.empty:
        c0, c1 = cats.iloc[0], cats.iloc[1] if len(cats) > 1 else None
        out["cat_a"] = (f"{c0['category']} take {pct(c0['share_pct'])} of every visitor dollar"
                        + (f", followed by {c1['category'].lower()} at {pct(c1['share_pct'])}" if c1 is not None else "")
                        + ". Lodging and dining together account for "
                        + pct(cats.head(2)["share_pct"].sum())
                        + ", so hotel performance and restaurant health are the two clearest reads on the visitor economy.")
    ads, mix = m.ads, m.ad_mix
    if ads:
        a = (f"Through {pdx.fmt_date(ads.get('snapshot_date'))}, the paid-media campaign delivered "
             f"{num_big(ads.get('total_impressions'))} impressions and {ads.get('total_clicks', 0):,.0f} clicks on "
             f"{usd(ads.get('total_spend_usd'))} in spend, for an estimated {usd_big(ads.get('est_campaign_impact_usd'))} "
             f"in visitor impact: about {usd(ads.get('est_roas'), 2)} returned for every $1 spent (Datafy estimate).")
        if mix is not None and not mix.empty:
            la = mix[mix["dma"] == "Los Angeles"]
            over = mix[(mix["trip_share_pct"].fillna(0) > mix["share_pct"].fillna(0) * 1.5)]
            under = mix[(mix["share_pct"].fillna(0) > 3) & (mix["trip_share_pct"].fillna(0) < 1)]
            if not la.empty and pd.notna(la.iloc[0]["trip_share_pct"]):
                a += (f" Campaign-attributed trips lean heavily on Los Angeles ({pct(la.iloc[0]['trip_share_pct'])} of trips, "
                      f"against its {pct(la.iloc[0]['share_pct'])} share of all visitor spending).")
            if not under.empty:
                u = under.iloc[0]
                a += (f" {clean_market(u['dma'])} delivers {pct(u['share_pct'])} of visitor spending but under 1% of "
                      f"campaign trips, the clearest gap between where spending comes from and where the media is landing.")
        out["ads_a"] = a
    return out


def write_market(m: Model) -> dict:
    out = {
        "question": "How does Dana Point compare with its peers and the wider market?",
        "answer": "CoStar and STR benchmark data is not available yet.",
        "peer_q": "How does Dana Point rank against peer coastal markets?",
        "peer_a": "",
        "bench_q": "How do Dana Point hotels compare with the submarket, Orange County, and the U.S.?",
        "bench_a": "",
        "tier_q": "Which hotel tiers lead the submarket?",
        "trend_q": "Is the market still growing, and how does it compare with Orange County and the nation?",
        "trend_a": "",
        "mix_q": "How much of the business is leisure versus group?",
        "mix_a": "",
    }
    p, b = m.peers, m.bench
    parts = []
    if p and p.get("dp"):
        dp, avg = p["dp"], p["peer_avg"]
        weeks = p["weeks"]
        if p["fallback"] or len(weeks) == 1:
            span = f"In the STR weekly report for the week ending {pdx.fmt_date(weeks[-1])}"
        else:
            span = f"Across the {len(weeks)} STR weekly reports in this window"
        out["peer_a"] = (f"{span}, Dana Point ranks {_ordinal(p['rank_revpar'])} of {p['n_markets']} coastal markets "
                         f"on RevPAR ({usd(dp['revpar'])}) and {_ordinal(p['rank_adr'])} on ADR ({usd(dp['adr'])}), but "
                         f"{_ordinal(p['rank_occ'])} on occupancy ({pct(dp['occ'])} against a peer average of "
                         f"{pct(avg['occ'])}). Put simply, Dana Point wins on rate and revenue and has room to grow on "
                         f"rooms sold. Its revenue index against the peer average is {p['rgi']:.0f} (100 is par).")
        if dp.get("revpar_pct") is not None:
            out["peer_a"] += (f" Dana Point RevPAR changed {spct(dp['revpar_pct'])} year over year "
                              f"{'that week' if len(weeks) == 1 else 'across those weeks'}.")
        parts.append(f"Dana Point ranks {_ordinal(p['rank_revpar'])} of {p['n_markets']} peer coastal markets on RevPAR "
                     f"and {_ordinal(p['rank_occ'])} on occupancy (STR weekly).")
    if b and b.get("comp"):
        t = b["table"].set_index("market")
        comp = b["comp"]
        through = pdx.fmt_month(b["through"])
        sub = t.loc["Newport Beach/Dana Point"] if "Newport Beach/Dana Point" in t.index else None
        oc = t.loc["Orange County"] if "Orange County" in t.index else None
        us = t.loc["United States"] if "United States" in t.index else None
        s = (f"Year to date through {through}, Dana Point hotels earned {usd(comp['revpar'])} RevPAR"
             + (f", against {usd(sub['revpar'])} for the Newport Beach/Dana Point submarket" if sub is not None else "")
             + (f", {usd(oc['revpar'])} for Orange County" if oc is not None else "")
             + (f", and {usd(us['revpar'])} nationally" if us is not None else "") + ".")
        if sub is not None:
            adr_gap = (comp["adr"] / sub["adr"] - 1) * 100
            occ_gap = comp["occ"] - sub["occ"]
            if adr_gap > 0 and occ_gap < 0:
                s += (f" The premium is rate, not volume: ADR of {usd(comp['adr'])} runs {abs(adr_gap):.0f}% above the "
                      f"submarket, while occupancy of {pct(comp['occ'])} sits {abs(occ_gap):.1f} points below it.")
            else:
                s += (f" ADR of {usd(comp['adr'])} is {abs(adr_gap):.0f}% {'above' if adr_gap >= 0 else 'below'} the submarket "
                      f"and occupancy of {pct(comp['occ'])} is {abs(occ_gap):.1f} points {'above' if occ_gap >= 0 else 'below'} it.")
        if comp.get("revpar_pct") is not None and sub is not None and pd.notna(sub.get("revpar_pct")):
            s += (f" Dana Point RevPAR grew {spct(comp['revpar_pct'])} on last year, "
                  f"{'faster than' if comp['revpar_pct'] > sub['revpar_pct'] else 'slower than'} the submarket's {spct(sub['revpar_pct'])}.")
        out["bench_a"] = s
        if b.get("rgi_sub"):
            gap = b["rgi_sub"] - 100
            parts.append(f"Year to date, Dana Point hotels {'lead' if gap >= 0 else 'trail'} the submarket on RevPAR by "
                         f"{abs(gap):.0f}% (CoStar).")
    my = m.multiyear
    if my is not None and not my.empty:
        sub = my[my["market"] == "Newport Beach/Dana Point"].sort_values("year_label")
        oc = my[my["market"] == "Orange County"].sort_values("year_label")
        if len(sub) >= 3:
            yrs = sub[sub["year_label"].str.fullmatch(r"\d{4}")]
            first = yrs.iloc[0] if not yrs.empty else sub.iloc[0]
            last_full = yrs.iloc[-1] if not yrs.empty else sub.iloc[-2]
            growth = (last_full["revpar_usd"] / first["revpar_usd"] - 1) * 100 if first["revpar_usd"] else None
            pre = yrs[yrs["year_label"] == "2019"]
            pre_txt = ""
            if not pre.empty and pre.iloc[0]["revpar_usd"]:
                g19 = (last_full["revpar_usd"] / pre.iloc[0]["revpar_usd"] - 1) * 100
                pre_txt = f", {abs(g19):.0f}% {'above' if g19 >= 0 else 'below'} the 2019 pre-pandemic level"
            out["trend_a"] = (f"Submarket RevPAR went from {usd(first['revpar_usd'])} in {first['year_label']} to "
                              f"{usd(last_full['revpar_usd'])} in {last_full['year_label']} ({spct(growth, 0)}){pre_txt}.")
            if not oc.empty:
                oc_last = oc[oc["year_label"] == last_full["year_label"]]
                if not oc_last.empty:
                    prem = (last_full["revpar_usd"] / oc_last.iloc[0]["revpar_usd"] - 1) * 100
                    out["trend_a"] += (f" In {last_full['year_label']} the submarket earned {abs(prem):.0f}% "
                                       f"{'more' if prem >= 0 else 'less'} RevPAR than Orange County overall.")
    sg = m.segments
    if sg:
        tot = sg["totals"].set_index("segment")
        tr = tot["share"].get("Transient")
        gp = tot["share"].get("Group")
        out["mix_a"] = (f"Transient (leisure and individual business) travelers bought {pct(tr, 0)} of occupied rooms in this "
                        f"window and group business {pct(gp, 0)} (CoStar segmentation, same comp set)."
                        if tr is not None and gp is not None else "")
        if gp is not None and "adr" in tot and pd.notna(tot["adr"].get("Group")) and pd.notna(tot["adr"].get("Transient")):
            out["mix_a"] += (f" Group rate averaged {usd(tot['adr']['Group'])} against {usd(tot['adr']['Transient'])} transient"
                             f"{', so group is not a discount segment here' if tot['adr']['Group'] >= tot['adr']['Transient'] * 0.97 else ''}.")
        if m.group and m.group.get("group_share") is not None:
            out["mix_a"] += (f" In the latest STR week (ending {pdx.fmt_date(m.group['week'])}), group filled "
                             f"{m.group['group_share']:.0f}% of occupied rooms.")
    if parts:
        out["answer"] = " ".join(parts)
    return out


def _ordinal(n: int) -> str:
    return {1: "first", 2: "second", 3: "third", 4: "fourth", 5: "fifth", 6: "sixth"}.get(n, f"#{n}")


def write_forward(m: Model) -> dict:
    out = {
        "question": "What is coming, and where should the team focus next?",
        "answer": "",
        "events_q": "Which upcoming events matter most, and how did those dates perform last year?",
        "events_a": "",
        "comp_q": "How often do hotels sell out, and is that rising?",
        "comp_a": "",
        "group_q": "How much of the latest week came from group business?",
        "group_a": "",
    }
    ev = m.events
    parts = []
    if ev is not None and not ev.empty:
        e0 = ev.iloc[0]
        lines = []
        for e in ev.head(4).itertuples():
            ly = f" (last year: {pct(e.ly_occ, 0)} occupancy at {usd(e.ly_adr)})" if pd.notna(getattr(e, "ly_occ", None)) else ""
            lines.append(f"{e.event_name} {days_phrase(int(e.days_out))}{ly}")
        out["events_a"] = "Next on the calendar: " + "; ".join(lines) + "."
        best = ev.dropna(subset=["ly_occ"]).sort_values("ly_occ", ascending=False) if "ly_occ" in ev else pd.DataFrame()
        if not best.empty:
            bb = best.iloc[0]
            out["events_a"] += (f" {bb['event_name']} dates were the strongest of this group last year, "
                                f"the clearest candidates for rate strategy and targeted campaigns.")
        parts.append(f"{e0['event_name']} is {days_phrase(int(e0['days_out']))}"
                     + (f"; the same dates last year ran {pct(e0['ly_occ'], 0)} occupancy" if pd.notna(e0.get("ly_occ")) else "")
                     + ".")
    cq = m.compression
    if cq is not None and not cq.empty:
        full = cq[cq["complete"]]
        cur = cq.iloc[-1]
        same_q_ly = cq[cq["quarter"] == f"{int(cur['quarter'][:4]) - 1}{cur['quarter'][4:]}"]
        s = (f"{cur['quarter']} has logged {plural(int(cur['d80']), 'night')} at 80% occupancy or higher"
             f"{' so far' if not cur['complete'] else ''}")
        if not same_q_ly.empty:
            if not cur["complete"] and m.daily is not None and not m.daily.empty:
                q_days = m.daily[m.daily["date"].dt.to_period("Q").astype(str).str.replace("Q", "-Q") == cur["quarter"]]
                if not q_days.empty:
                    ly = m.daily[(m.daily["date"] >= q_days["date"].min() - pd.Timedelta(days=364)) &
                                 (m.daily["date"] <= q_days["date"].max() - pd.Timedelta(days=364))]
                    s += (f", against {int((ly['occ_pct'] >= 80).sum())} over the same days last year and "
                          f"{int(same_q_ly.iloc[0]['d80'])} in all of {same_q_ly.iloc[0]['quarter']}")
            else:
                s += f", against {int(same_q_ly.iloc[0]['d80'])} in {same_q_ly.iloc[0]['quarter']}"
        s += "."
        if len(full) >= 5:
            last4 = full.tail(4)["d80"].sum()
            prev4 = full.iloc[-8:-4]["d80"].sum() if len(full) >= 8 else None
            if prev4:
                s += f" The last four full quarters produced {last4} compression nights versus {prev4} the year before."
        out["comp_a"] = s
    g = m.group
    if g and g.get("group_share") is not None:
        out["group_a"] = (f"In the STR week ending {pdx.fmt_date(g['week'])}, Dana Point ran {pct(g['total_occ'])} occupancy, and "
                          f"group business filled {g['group_share']:.0f}% of occupied rooms. Group bookings are the "
                          f"most controllable lever for the softer midweek nights shown in the Performance Snapshot.")
    mo = m.momentum
    if mo and mo.get("revpar_pct") is not None:
        parts.append(f"Momentum is {'positive' if mo['revpar_pct'] > 0 else 'negative'}: the latest four weeks of hotel RevPAR "
                     f"are {spct(mo['revpar_pct'])} year over year.")
    wk = m.wk
    if wk:
        parts.append(f"The biggest opening remains midweek, where occupancy trails weekends by {wk['occ_gap']:.0f} points.")
    out["answer"] = " ".join(parts) if parts else "Forward-looking data is not available yet."
    return out


def write_glance(m: Model, snap: dict, vis: dict, mkt: dict, fwd: dict) -> list[dict]:
    """Four takeaways for the top of the page, one per section, each a
    headline plus one supporting sentence."""
    out = []
    h = m.hotel
    if h and h.get("prior"):
        out.append({"icon": "hotel", "title": f"Hotel revenue per room {updown(h['revpar_pct'])} {mag(h['revpar_pct'])}",
                    "body": f"{pct(h['occ'])} occupancy ({pts(h['occ_pts'])}) at {usd(h['adr'])} ADR ({spct(h['adr_pct'])}) "
                            f"for {_window_phrase(m)}.", "anchor": "pulse-snapshot"})
    elif h:
        out.append({"icon": "hotel", "title": f"RevPAR {usd(h['revpar'])}",
                    "body": f"{pct(h['occ'])} occupancy at {usd(h['adr'])} ADR for {_window_phrase(m)}.", "anchor": "pulse-snapshot"})
    p = m.peers
    b = m.bench
    if p and p.get("dp"):
        out.append({"icon": "market", "title": f"{_ordinal(p['rank_revpar']).capitalize()} of {p['n_markets']} coastal markets on RevPAR",
                    "body": f"Leads peers on rate ({usd(p['dp']['adr'])} ADR) but ranks {_ordinal(p['rank_occ'])} on occupancy."
                            + (f" Year to date, RevPAR is {b['rgi_sub'] - 100:.0f}% above the submarket." if b and b.get("rgi_sub") else ""),
                    "anchor": "pulse-market"})
    d = m.dfy
    if d and d.get("spend") is not None:
        span = f"{pdx.fmt_month(d['first'])} to {pdx.fmt_month(d['last'])}" if d["n_months"] > 1 else pdx.fmt_month(d["first"])
        out.append({"icon": "visitors", "title": f"Visitor spending {usd_big(d['spend'])}"
                                                 + (f", {updown(d['spend_pct'])} {mag(d['spend_pct'])}"
                                                    if d.get("spend_pct") is not None and not d.get("fallback") else ""),
                    "body": ((f"Latest Datafy month ({span})" + (f", {spct(d['spend_pct'])} on the same month last year."
                                                                 if d.get("spend_pct") is not None else "."))
                             if d.get("fallback") else
                             f"{span}, Datafy." + (f" Visitor days {spct(d.get('vd_pct'))}; "
                                                   f"{clean_market(m.markets.iloc[0]['dma'])} leads all markets."
                                                   if d.get("vd_pct") is not None and m.markets is not None and not m.markets.empty else "")),
                    "anchor": "pulse-origins"})
    ev = m.events
    if ev is not None and not ev.empty:
        e0 = ev.iloc[0]
        out.append({"icon": "calendar", "title": f"{e0['event_name']} {days_phrase(int(e0['days_out']))}",
                    "body": (f"Same dates last year: {pct(e0['ly_occ'], 0)} occupancy at {usd(e0['ly_adr'])}. " if pd.notna(e0.get("ly_occ")) else "")
                            + (f"Last four weeks RevPAR {spct(m.momentum['revpar_pct'])} year over year." if m.momentum and m.momentum.get("revpar_pct") is not None else ""),
                    "anchor": "pulse-forward"})
    return out


def write_all(m: Model) -> dict:
    snap = write_snapshot(m)
    vis = write_visitors(m)
    mkt = write_market(m)
    fwd = write_forward(m)
    return {"snapshot": snap, "visitors": vis, "market": mkt, "forward": fwd,
            "glance": write_glance(m, snap, vis, mkt, fwd)}


def page_context(m: Model) -> str:
    """Everything the page says, as plain text, for the AI prompts. Handing
    the model the page's own computed answers keeps an AI response from
    contradicting the tiles and charts the reader is looking at."""
    if m is None:
        return ""
    t = m.text
    lines = [f"Selected window: {m.window.label} ({_window_phrase(m)})."]
    for g in t.get("glance", []):
        lines.append(f"At a glance: {g['title']}. {g['body']}")
    for key in ("snapshot", "visitors", "market", "forward"):
        sec = t.get(key, {})
        for k, v in sec.items():
            if k.endswith("_q") or k == "question" or not v:
                continue
            lines.append(f"[{key}] {v}")
    return "\n".join(lines)
