[theme]
base = "dark"
primaryColor = "#00D4C8"
backgroundColor = "#1A3756"
secondaryBackgroundColor = "#1E3D5E"
textColor = "#F4FAFF"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
